version: '3.4'

services:
  api_docs:
    container_name: api-docs
    restart: always
    image: bireme/api-documentation:latest
    ports:
        - ${APP_PORT}:8080
    env_file:
        - .env
    networks:
        - nginx-proxy

networks:
  nginx-proxy:
    external: true
