version: '3.4'

services:
  api_docs:
    container_name: api-docs
    restart: "no"
    image: swaggerapi/swagger-ui
    ports:
        - ${APP_PORT}:8080
    volumes:
        - ./apis:/usr/share/nginx/html/apis
        - ./custom/index.css:/usr/share/nginx/html/index.css
    env_file:
        - .env
    networks:
        - nginx-proxy

networks:
  nginx-proxy:
    external: true
