openapi: 3.0.3
info:
  title: Events Directory API (DirEve)
  description: |-
     Information about scientific events in the health field, such as congresses, seminars, conferences, etc., primarily taking place in Latin America and the Caribbean.

     DirEve is updated by more than 70 institutions that are members of the VHL Network and coordinated by BIREME.
  version: V1
servers:
  - url: https://api.bvsalud.org/event/v1/

paths:
  /:
    get:
      tags:
        - List events
      summary: List events from the directory
      description:
      operationId: list
      parameters:
        - name: limit
          in: query
          description: The limit parameter specifies the number of items that a single response contains. Example **10**
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The offset parameter is used to exclude from a response the first N items of the result. Example **20**
          required: false
          schema:
            type: integer
        - name: format
          in: query
          description: The format parameter control the output format of the result.
          required: false
          schema:
            type: string
            default: json
            enum:
              - json
              - xml
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized. Apikey code not provided or invalid
        '404':
          description: Result not found or result error
      security:
        - apikey: []

  /next/:
    get:
      tags:
        - Next events
      summary: Return next events based on the current date
      description:
      operationId: NextEvents
      parameters:
        - name: fq
          in: query
          description: The fq parameter is used to filter the result by a expression. Example **country:"Brasil"**
          required: false
          schema:
            type: string
        - name: lang
          in: query
          description: The lang parameter is used to return DeCS descriptors at specific language.
          required: false
          schema:
            type: string
            default: pt
            enum:
              - pt
              - es
              - en
        - name: format
          in: query
          description: The format parameter control the output format of the result.
          required: false
          schema:
            type: string
            default: json
            enum:
              - json
              - xml
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized. Apikey code not provided or invalid
        '404':
          description: Result not found or result error
      security:
        - apikey: []



  /search/:
    get:
      tags:
        - Search events
      summary: Search events by query expression
      description:
      operationId: searchByWords
      parameters:
        - name: q
          in: query
          description: |-
              The q parameter is used to inform a expression to be searched.

              It's possible to use boolean operators **(AND, OR, AND NOT)** in the query expression.

              Example **public AND health**
          required: true
          explode: true
          schema:
            type: string
        - name: fq
          in: query
          description: The fq parameter is used to filter the result by a expression. Example **country:"Brasil"**
          required: false
          schema:
            type: string
        - name: lang
          in: query
          description: The lang parameter is used to return DeCS descriptors at specific language.
          required: false
          schema:
            type: string
            default: pt
            enum:
              - pt
              - es
              - en
        - name: count
          in: query
          description: The count parameter specifies the number of items that a single response contains. Example **10**
          required: false
          schema:
            type: integer
        - name: start
          in: query
          description: The start parameter is used to exclude from a response the first N items of the result. Example **20**
          required: false
          schema:
            type: integer
        - name: format
          in: query
          description: The format parameter control the output format of the result.
          required: false
          schema:
            type: string
            default: json
            enum:
              - json
              - xml
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized. Apikey code not provided or invalid
        '404':
          description: Result not found or result error
      security:
        - apikey: []

components:
  securitySchemes:
    apikey:
      type: apiKey
      name: apikey
      in: header
