name: Docker Image CI
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-tags: true
          fetch-depth: 10
    - name: Docker Login - Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Get tag version
      id: get_tag
      run: |
        echo "TAG=$(git describe --tags --long --always | sed 's/-g[a-z0-9]\{7\}//' | sed 's/-/\./')" >> $GITHUB_OUTPUT
  
    - name: Build and push docker image
      run: |
        echo "TAG IMAGE VERSION: ${{ steps.get_tag.outputs.TAG }}"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs:latest
        docker tag ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs:latest ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs:${{ steps.get_tag.outputs.TAG }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs --all-tags
