name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login - Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    - name: Build and push docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs:latest
        docker push ${{ secrets.DOCKER_REGISTRY }}/bireme/api-docs
